### ISSUE TITLE
Something went wrong while loading “kap-streamable”  - @3.2.2

### ISSUE THREAD

**Issue by thehackermonkey** [kevva/kap-streamable#5]
Not sure if this is an issue with the plugin or the main app.

### How to reproduce

* Install Kap 3.2.2
* Try to turn on the streamable plugin directly from the preferences panel

```
Something went wrong while loading “kap-streamable”
Error: schema is invalid: data.properties['password'].type should be equal to one of the allowed values, data.properties['password'].type should be array, data.properties['password'].type should match some schema in anyOf
    at CustomAjv.validateSchema (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/ajv/lib/ajv.js:178:16)
    at CustomAjv._addSchema (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/ajv/lib/ajv.js:307:10)
    at CustomAjv.compile (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/ajv/lib/ajv.js:113:24)
    at /Applications/Kap.app/Contents/Resources/app.asar/main/utils/plugin-config.js:35:29
    at Array.map (<anonymous>)
    at new PluginConfig (/Applications/Kap.app/Contents/Resources/app.asar/main/utils/plugin-config.js:8:81)
    at new InstalledPlugin (/Applications/Kap.app/Contents/Resources/app.asar/main/plugin.js:48:21)
    at Plugins.install (/Applications/Kap.app/Contents/Resources/app.asar/main/common/plugins.js:126:22)
```

**Comment by ksdavidc** [comment]
I have the same problem.
